### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by hejunN** [wangsiwei2010/FPMVS-CAG#1]
您好，请问计算fscore的compute_f文件是按哪种方式计算的呢？感觉既不是macro也不是micro版的f-score.

**Comment by wangsiwei2010** [comment]
您好，聚类结果的评价为之前大部分聚类文章的所用函数，比如（code）[https://github.com/sckangz/mPAC/blob/master/Clustering8Measure.m]，同时可以在大量公开代码得到。我们马上查看compute_f函数，有结果后回复您。

**Comment by hejunN** [comment]
好的，十分感谢您的回复，期待您的解惑。
