### ISSUE TITLE
请教信

### ISSUE THREAD

**Issue by zhang-yan1125** [wangsiwei2010/FPMVS-CAG#2]
师兄打扰了，请问代码文件“algo_qp.p“的.m版本是否可以提供，研一学生想要仔细研究该算法的相关实现过程，仅用于个人课题研究，若能提供，万分感激！

**Comment by wangsiwei2010** [comment]
可参考https://github.com/Jeaninezpp/SMVSC

**Comment by zhang-yan1125** [comment]
收到，感谢回复。
